typography_spectrum: 0.1410946969408542
color:
  brandStrength: 0.7353205964900553
  lightness: 0.6021420343313366
  saturation: 0.5534599001985043
  rhythmicContrast: 0.8968854150734842
  brandColors:
    - '#050505'
    - '#4C4C4C'
    - '#832C0B'
    - '#B27F4F'
    - '#30807F'
layout_spectrum: 0.04753226274624467
author:
  name: Eduard Samokhvalov
  email: eduard@packandsell.org
  url: www.packandsell.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c4da7f2-cecb-49dc-9386-106bc19b412b.jpg
name: Futurism | Iconography | surrealism | Symbolism
title: Andrey Zhokhov
description: Portfolio Presentation
